# postgres
#default environment, will work with postgres
default: &default
  adapter: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
#enviroment development
development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
#environment test
test:
  <<: *default
  url: <%= ENV['TEST_DATABASE_URL'] %>